server:
  port: 9000
  
spring:
  profiles:
    active: native  
  cloud:
    config:
      server:
        native:
          searchLocations: file:D:/configuration
        monitor: 
          github: false
          
#  cloud:
#    config:
#      server:
#        git: 
#          uri: https://github.com/rollingstoneecomm/rollingstone-ecommerce-remote-config-repository
#          searchPaths: rollingstone-ecommerce-new-account-api,rollingstone-ecommerce-address-api,rollingstone-ecommerce-order-api,rollingstone-ecommerce-user-api,rollingstone-ecommerce-account-api,rollingstone-ecommerce-add-to-cart-api,rollingstone-ecommerce-category-api,rollingstone-ecommerce-checkout-api,rollingstone-ecommerce-delivery-api,rollingstone-ecommerce-ecoupon-api,rollingstone-ecommerce-pricing-api,rollingstone-ecommerce-product-api,rollingstone-ecommerce-promo-api,rollingstone-ecommerce-shipping-api,rollingstone-ecommerce-spu-api
#          username: rollingstoneecomm
#          password: KeepLearning$$1
          
  datasource:
    url: jdbc:mysql://localhost:3306/rs_ecommerce?useSSL=false
    username: root
    password: 1q9b8e1x
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          validationQuery: SELECT 1
          ddl-auto: update          
          
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"