server:
  port: 8761
  tomcat:
    accesslog:
      enabled: true
      directory: /logs  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/